# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/Fit2D.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fit2D(object):
    def setupUi(self, Fit2D):
        Fit2D.setObjectName("Fit2D")
        Fit2D.resize(680, 624)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Fit2D)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.UpperPlots = QtWidgets.QHBoxLayout()
        self.UpperPlots.setObjectName("UpperPlots")
        self.verticalLayout_2.addLayout(self.UpperPlots)
        self.MainPlot = QtWidgets.QFrame(Fit2D)
        self.MainPlot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainPlot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainPlot.setObjectName("MainPlot")
        self.verticalLayout_2.addWidget(self.MainPlot)
        self.BottomPanel = QtWidgets.QHBoxLayout()
        self.BottomPanel.setObjectName("BottomPanel")
        self.verticalLayout_2.addLayout(self.BottomPanel)

        self.retranslateUi(Fit2D)
        QtCore.QMetaObject.connectSlotsByName(Fit2D)

    def retranslateUi(self, Fit2D):
        _translate = QtCore.QCoreApplication.translate
        Fit2D.setWindowTitle(_translate("Fit2D", "Form"))
