from typing import Protocol

class Displayer(Protocol):

    def display_home_page(self): ...
    
    def display_measurement(self, measurement): ...

    def display_fit(self, fit): ...

    def display_tau_fit(self, tau_fit): ...